force-app/main/default/objects/WhatsappMeta__mdt/WhatsappMeta__mdt.object-meta.xml
<CustomObject>
    <label>Whatsapp Meta</label>
    <pluralLabel>WhatsappMeta</pluralLabel>
</CustomObject>

force-app/main/default/objects/WhatsappMeta__mdt/fields/AccessToken__c.field-meta.xml
<CustomField>
    <fullName>AccessToken__c</fullName>
    <label>Access Token</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WhatsappMeta__mdt/fields/Business_Number__c.field-meta.xml
<CustomField>
    <fullName>Business_Number__c</fullName>
    <label>Business Number</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WhatsappMeta__mdt/fields/PhoneNumber_Id__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber_Id__c</fullName>
    <label>Phone Number Id</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsappMeta__mdt/fields/WABA_Id__c.field-meta.xml
<CustomField>
    <fullName>WABA_Id__c</fullName>
    <label>Whatsapp Bussiness Account Id</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/WhatsAppMetaTemplate__c.object-meta.xml
<CustomObject>
    <label>WhatsApp Meta Template</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Meta Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WhatsApp Meta Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/CorrectCategory__c.field-meta.xml
<CustomField>
    <fullName>CorrectCategory__c</fullName>
    <label>Correct Category</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <externalId>true</externalId>
    <label>Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/language__c.field-meta.xml
<CustomField>
    <fullName>language__c</fullName>
    <label>language</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/SubCategory__c.field-meta.xml
<CustomField>
    <fullName>SubCategory__c</fullName>
    <label>Sub Category</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/Template_Footer__c.field-meta.xml
<CustomField>
    <fullName>Template_Footer__c</fullName>
    <label>Template Footer</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/Template_Header__c.field-meta.xml
<CustomField>
    <fullName>Template_Header__c</fullName>
    <label>Template Header</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Template_Name__c</fullName>
    <label>Template Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateButtonOfferCode__c.field-meta.xml
<CustomField>
    <fullName>TemplateButtonOfferCode__c</fullName>
    <label>Template Button OfferCode</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateButtonPhone__c.field-meta.xml
<CustomField>
    <fullName>TemplateButtonPhone__c</fullName>
    <label>Template Button Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateButtonText__c.field-meta.xml
<CustomField>
    <fullName>TemplateButtonText__c</fullName>
    <label>Template Button Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateButtonType__c.field-meta.xml
<CustomField>
    <fullName>TemplateButtonType__c</fullName>
    <label>Template Button Type</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateButtonURL__c.field-meta.xml
<CustomField>
    <fullName>TemplateButtonURL__c</fullName>
    <label>Template Button URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateHeaderHandler__c.field-meta.xml
<CustomField>
    <fullName>TemplateHeaderHandler__c</fullName>
    <label>Template Header Handler</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateHeaderText__c.field-meta.xml
<CustomField>
    <fullName>TemplateHeaderText__c</fullName>
    <label>Template Header Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/SyncTemplateControlleer.cls
public class SyncTemplateControlleer {
    
    @AuraEnabled
    public static String syncTemplate(String recordId) {
        WhatsAppMetaTemplate__c template = [SELECT Id, Id__c FROM WhatsAppMetaTemplate__c WHERE Id = :recordId LIMIT 1];
        String result = FetchTemplate(template.Id__c);
        return result;
    }

    public static String FetchTemplate(String templateId) {
        List<WhatsAppMetaTemplate__c> messages = new List<WhatsAppMetaTemplate__c>();

        try {
            List<WhatsappMeta__mdt> businessList = [SELECT Id, Version__c, AccessToken__c, PhoneNumber_Id__c, WABA_Id__c, Business_Number__c FROM WhatsappMeta__mdt LIMIT 1];
            
            if (businessList.isEmpty()) {
                return 'Error: No WhatsApp business metadata found.';
            }
 
            WhatsappMeta__mdt business = businessList[0];
            HttpRequest req = new HttpRequest();
            req.setEndpoint('https://graph.facebook.com/' + business.Version__c + '/' + templateId);
            req.setMethod('GET');
            req.setHeader('Authorization', 'Bearer ' + business.AccessToken__c);

            HttpResponse res = new Http().send(req);

            if (res.getStatusCode() == 200) {
                String responseBody = res.getBody();
                System.debug('API Response: ' + responseBody);

                WhatsAppTemplate template = (WhatsAppTemplate) JSON.deserialize(responseBody, WhatsAppTemplate.class);

                WhatsAppMetaTemplate__c newTemplate = new WhatsAppMetaTemplate__c();
                newTemplate.Id__c = template.id;
                newTemplate.Category__c = template.category;
                newTemplate.Template_Name__c = template.name;
                newTemplate.Status__c = template.status;
                //newTemplate.SubCategory__c = template.sub_category;
                newTemplate.CorrectCategory__c = template.correct_category;
                newTemplate.Language__c= template.language;

                if (template.components != null) {
                    for (WhatsAppTemplate.Component comp : template.components) {
                        if (comp.type == 'HEADER') {
                            newTemplate.Template_Header__c = comp.format;
                            if (comp.example != null && comp.example.header_handle != null && !comp.example.header_handle.isEmpty()) {
                               // newTemplate.TemplateHeaderHandler__c = comp.example.header_handle[0];
                            }
                            newTemplate.TemplateHeaderText__c = comp.text;
                        } else if (comp.type == 'BODY') {
                            newTemplate.Template_Body__c = comp.text;
                        } else if (comp.type == 'FOOTER') {
                            newTemplate.Template_Footer__c = comp.text;
                        } else if (comp.type == 'BUTTONS' && comp.buttons != null) {
                            List<String> buttonTypes = new List<String>();
                            List<String> buttonTexts = new List<String>();
                            List<String> offerCodes = new List<String>();
                            List<String> phones = new List<String>();
                            List<String> urls = new List<String>();

                            for (WhatsAppTemplate.Button btn : comp.buttons) {
                                buttonTypes.add(btn.type);
                                buttonTexts.add(btn.text);

                                if (btn.type == 'COPY_CODE' && btn.example != null && !btn.example.isEmpty()) {
                                    offerCodes.addAll(btn.example);
                                } else if (btn.type == 'PHONE_NUMBER' && btn.phone_number != null) {
                                    phones.add(btn.phone_number);
                                } else if (btn.type == 'URL' && btn.url != null) {
                                    urls.add(btn.url);
                                }
                            }

                            newTemplate.TemplateButtonType__c = String.join(buttonTypes, ',');
                            newTemplate.TemplateButtonText__c = String.join(buttonTexts, ',');
                            newTemplate.TemplateButtonOfferCode__c = String.join(offerCodes, ',');
                            newTemplate.TemplateButtonPhone__c = String.join(phones, ',');
                            newTemplate.TemplateButtonURL__c = String.join(urls, ',');
                        }
                    }
                }
                messages.add(newTemplate);

            } else {
                return 'API Error: ' + res.getStatusCode() + ' - ' + res.getStatus() +'-'+ res.getBody();
            }
        } catch (Exception e) {
            return 'Exception: ' + e.getMessage();
        }
        if (!messages.isEmpty()) {
            upsert messages Id__c;
            return 'Template synced successfully.';
        } else {
            return 'No data to sync.';
        }
    }
}