force-app/main/default/objects/WhatsAppMessagingSession__c/WhatsAppMessagingSession__c.object-meta.xml
<CustomObject>
    <label>WhatsApp Messaging Session</label>
    <nameField>
        <displayFormat>WMS-{0000}</displayFormat>
        <label>WhatsApp Messaging Session</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WhatsApp Messaging Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WhatsAppMessagingSession__c/fields/BusinessPhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>BusinessPhoneNumber__c</fullName>
    <label>Business Phone Number</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WhatsAppMessagingSession__c/fields/CustomerPhone__c.field-meta.xml
<CustomField>
    <fullName>CustomerPhone__c</fullName>
    <label>Customer Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WhatsAppMessagingSessionHandler.cls
public class WhatsAppMessagingSessionHandler {
    public static void sendImages(Set<Id> ids) {
        List<WhatsAppMessagingSession__c> sessions = [SELECT Id, CustomerName__c, CustomerPhone__c, BusinessPhoneNumber__c FROM WhatsAppMessagingSession__c
                                                      WHERE Id IN :ids];
        Map<Id, WhatsAppMessagingSession__c> mapSession = new Map<Id, WhatsAppMessagingSession__c>(sessions);
        
        String msgBody = 'Links';
        
        for (Id sessionId : mapSession.keySet()) {
            WhatsAppMessagingSession__c session = mapSession.get(sessionId);
            if (session.CustomerPhone__c == null || session.BusinessPhoneNumber__c == null || session.CustomerName__c == null) {
                System.debug('Skipping session due to missing required fields: ' + sessionId);
                continue;
            }
            String calloutString = session.CustomerPhone__c + '@@' +session.BusinessPhoneNumber__c + '@@' +msgBody + '@@' +'image' + '@@' +null + '@@' +null + '@@' +session.CustomerName__c;
            System.debug('MessagingSession Handler Callout ==> ' + calloutString);
            WhatsAppOutgoingMessage.sendMediaMessage(calloutString);
        }
    }
}