force-app/main/default/objects/MessageLog__c/MessageLog__c.object-meta.xml
<CustomObject>
    <label>Message Log</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>Message Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Message Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WhatsappMeta__mdt/WhatsappMeta__mdt.object-meta.xml
<CustomObject>
    <label>Whatsapp Meta</label>
    <pluralLabel>WhatsappMeta</pluralLabel>
</CustomObject>

force-app/main/default/objects/WhatsappMeta__mdt/fields/AccessToken__c.field-meta.xml
<CustomField>
    <fullName>AccessToken__c</fullName>
    <label>Access Token</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WhatsappMeta__mdt/fields/Meta_URL__c.field-meta.xml
<CustomField>
    <fullName>Meta_URL__c</fullName>
    <label>Meta URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/WhatsappMeta__mdt/fields/PhoneNumber_Id__c.field-meta.xml
<CustomField>
    <fullName>PhoneNumber_Id__c</fullName>
    <label>Phone Number Id</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsappMeta__mdt/fields/WABA_Id__c.field-meta.xml
<CustomField>
    <fullName>WABA_Id__c</fullName>
    <label>Whatsapp Bussiness Account Id</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/WhatsAppMetaTemplate__c.object-meta.xml
<CustomObject>
    <label>WhatsApp Meta Template</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Meta Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WhatsApp Meta Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <externalId>true</externalId>
    <label>Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/SubCategory__c.field-meta.xml
<CustomField>
    <fullName>SubCategory__c</fullName>
    <label>Sub Category</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateHeaderHandler__c.field-meta.xml
<CustomField>
    <fullName>TemplateHeaderHandler__c</fullName>
    <label>Template Header Handler</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CreateMetaTemplate.cls
public class CreateMetaTemplate {
    // Custom response class to encapsulate the response details
    public class MetaTemplateResponse {
        @AuraEnabled
        public Boolean isSuccess;
        @AuraEnabled
        public String message;
        @AuraEnabled
        public String templateId;
        @AuraEnabled
        public String status;
        @AuraEnabled
        public String category;
    }
    
    @AuraEnabled
    public static MetaTemplateResponse createMetaTemplate(String body, string templateType, String distUrl) {
        System.debug('body = ' + body);
        System.debug('body = ' + templateType);
                System.debug('distUrl = ' + distUrl);


        MetaTemplateResponse response = new MetaTemplateResponse();
        List<WhatsAppMetaTemplate__c> wmtList = new List<WhatsAppMetaTemplate__c>();
        
        WhatsappMeta__mdt metadata = [SELECT Id,Version__c, AccessToken__c,PhoneNumber_Id__c,WABA_Id__c,Meta_URL__c FROM WhatsappMeta__mdt LIMIT 1];
        
        HttpRequest req = new HttpRequest();
        req.setEndpoint(metadata.Meta_URL__c+''+metadata.Version__c+'/' +metadata.WABA_Id__c+ '/message_templates');
        req.setMethod('POST');
         req.setHeader('Authorization', 'Bearer ' + metadata.AccessToken__c);
        req.setHeader('Content-Type', 'application/json');
        req.setBody(body);
        
        Http http = new Http();
        HttpResponse res = http.send(req);
        System.debug('Response status code: ' + res.getStatusCode());
        
        if (res.getStatusCode() == 200) {
            System.debug('Template created successfully: ' + res.getBody());
            
            Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
            WhatsAppMetaTemplate__c WmObj = new WhatsAppMetaTemplate__c();
            WmObj.Id__c = (String) responseMap.get('id');
            WmObj.Status__c = (String) responseMap.get('status');
            WmObj.Category__c = (String) responseMap.get('category');
            WmObj.SubCategory__c = templateType;
            WmObj.TemplateHeaderHandler__c = distUrl;
            wmtList.add(WmObj);
            
            if (!wmtList.isEmpty()) {
                insert wmtList;
                response.isSuccess = true;
                response.message = 'Template created and inserted successfully.';
                response.templateId = WmObj.Id__c;
                response.status = WmObj.Status__c;
                response.category = WmObj.Category__c;
            } else {
                response.isSuccess = false;
                response.message = 'Failed to insert template list.';
             
                MessageLog__c appLog = New MessageLog__c ();
                appLog.Description__c = res.getBody();
                Insert appLog;
            }
        } else {
            response.isSuccess = false;
            
            MessageLog__c appLog = New MessageLog__c ();
            appLog.Description__c = res.getBody();
            Insert appLog;
            
            response.message = 'Failed to create template. Status code: ' + res.getStatusCode() + ' Response: ' + res.getBody();
        }
        
        return response;
    }

    
    
    
    public static void dummy(){
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}