force-app/main/default/objects/WhatsAppMetaTemplate__c/WhatsAppMetaTemplate__c.object-meta.xml
<CustomObject>
    <label>WhatsApp Meta Template</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Meta Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WhatsApp Meta Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Template_Name__c</fullName>
    <label>Template Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateJSON__c.field-meta.xml
<CustomField>
    <fullName>TemplateJSON__c</fullName>
    <label>Template JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WhatsappUser__c/WhatsappUser__c.object-meta.xml
<CustomObject>
    <label>Whatsapp User</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Whatsapp User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Whatsapp Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WhatsappUser__c/fields/BusinessNumber__c.field-meta.xml
<CustomField>
    <fullName>BusinessNumber__c</fullName>
    <label>Business Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsappUser__c/fields/CustomerName__c.field-meta.xml
<CustomField>
    <fullName>CustomerName__c</fullName>
    <label>Customer Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WhatsappBulkSenderListViewController.cls
public class WhatsappBulkSenderListViewController {
      @AuraEnabled
    public static WhatsAppMetaTemplate__c getTemplateById(Id templateId) {
        system.debug('templateId=>'+templateId);
        WhatsAppMetaTemplate__c templateList = [SELECT Id, Template_Name__c, TemplateJSON__c FROM WhatsAppMetaTemplate__c WHERE Id = :templateId LIMIT 1];
                system.debug('templateList=>'+templateList);

        return templateList;
    }

    @AuraEnabled
    public static List<WhatsappUser__c> getUsers() {
        return [
            SELECT Id, BusinessNumber__c, CustomerPhone__c, CustomerName__c 
            FROM WhatsappUser__c LIMIT 4900
        ];
    }
}