force-app/main/default/objects/WhatsAppMetaTemplate__c/WhatsAppMetaTemplate__c.object-meta.xml
<CustomObject>
    <label>WhatsApp Meta Template</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Meta Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WhatsApp Meta Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/CorrectCategory__c.field-meta.xml
<CustomField>
    <fullName>CorrectCategory__c</fullName>
    <label>Correct Category</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/language__c.field-meta.xml
<CustomField>
    <fullName>language__c</fullName>
    <label>language</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/SubCategory__c.field-meta.xml
<CustomField>
    <fullName>SubCategory__c</fullName>
    <label>Sub Category</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/Template_Footer__c.field-meta.xml
<CustomField>
    <fullName>Template_Footer__c</fullName>
    <label>Template Footer</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/Template_Header__c.field-meta.xml
<CustomField>
    <fullName>Template_Header__c</fullName>
    <label>Template Header</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Template_Name__c</fullName>
    <label>Template Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateButtonOfferCode__c.field-meta.xml
<CustomField>
    <fullName>TemplateButtonOfferCode__c</fullName>
    <label>Template Button OfferCode</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateButtonPhone__c.field-meta.xml
<CustomField>
    <fullName>TemplateButtonPhone__c</fullName>
    <label>Template Button Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateButtonText__c.field-meta.xml
<CustomField>
    <fullName>TemplateButtonText__c</fullName>
    <label>Template Button Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateButtonType__c.field-meta.xml
<CustomField>
    <fullName>TemplateButtonType__c</fullName>
    <label>Template Button Type</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateButtonURL__c.field-meta.xml
<CustomField>
    <fullName>TemplateButtonURL__c</fullName>
    <label>Template Button URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateHeaderHandler__c.field-meta.xml
<CustomField>
    <fullName>TemplateHeaderHandler__c</fullName>
    <label>Template Header Handler</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateHeaderText__c.field-meta.xml
<CustomField>
    <fullName>TemplateHeaderText__c</fullName>
    <label>Template Header Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateJSON__c.field-meta.xml
<CustomField>
    <fullName>TemplateJSON__c</fullName>
    <label>Template JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TemplateMessageController.cls
public with sharing class TemplateMessageController {

    @AuraEnabled(cacheable=true)
    public static TemplateWrapper getTemplateData(Id recordId) {
        WhatsAppMetaTemplate__c record = [
            SELECT Template_Body__c,
                   TemplateButtonType__c,
                   Template_Footer__c,
                   Template_Header__c,
                   Template_Name__c,
                   TemplateHeaderText__c,
                   TemplateHeaderHandler__c,
                   TemplateButtonPhone__c,
                   TemplateButtonURL__c,
                   TemplateButtonOfferCode__c,
                   TemplateButtonText__c,
                   SubCategory__c,
                   CorrectCategory__c,
                   TemplateJSON__c,
                   language__c
            FROM WhatsAppMetaTemplate__c
            WHERE Id = :recordId
            LIMIT 1
        ];

        TemplateWrapper tw = new TemplateWrapper();
        tw.templateName = record.Template_Name__c;
        tw.headerType = record.Template_Header__c;
        tw.headerHandle = record.TemplateHeaderHandler__c;
        tw.headerText = record.TemplateHeaderText__c;
        tw.bodyText = record.Template_Body__c;
        tw.footerText = record.Template_Footer__c;

        tw.buttonType = record.TemplateButtonType__c;
        tw.buttonText = record.TemplateButtonText__c;
        tw.buttonPhone = record.TemplateButtonPhone__c;
        tw.buttonUrl = record.TemplateButtonURL__c;
        tw.buttonOfferCode = record.TemplateButtonOfferCode__c;

        tw.language = record.language__c;
        tw.category = record.CorrectCategory__c;
        tw.templateJSON = record.TemplateJSON__c;

        return tw;
    }

    @AuraEnabled
    public static void addJson(Id recordId, String jsonResponese) {
        system.debug('jsonResponese:'+jsonResponese);
        if (recordId != null && !String.isBlank(jsonResponese)) {
            update new WhatsAppMetaTemplate__c(
                Id = recordId,
                TemplateJSON__c = jsonResponese
            );
        }
    }

    public class TemplateWrapper {
        @AuraEnabled public String templateName;
        @AuraEnabled public String headerType;
        @AuraEnabled public String headerHandle;
        @AuraEnabled public String headerText;
        @AuraEnabled public String bodyText;
        @AuraEnabled public String footerText;

        @AuraEnabled public String buttonType;
        @AuraEnabled public String buttonText;
        @AuraEnabled public String buttonPhone;
        @AuraEnabled public String buttonUrl;
        @AuraEnabled public String buttonOfferCode;

        @AuraEnabled public String language;
        @AuraEnabled public String category;
        @AuraEnabled public String templateJSON;
    }
}