force-app/main/default/objects/WhatsAppMetaTemplate__c/WhatsAppMetaTemplate__c.object-meta.xml
<CustomObject>
    <label>WhatsApp Meta Template</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Meta Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WhatsApp Meta Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <externalId>true</externalId>
    <label>Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Template_Name__c</fullName>
    <label>Template Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TemplateInsights.cls
public class TemplateInsights {
    public static void insightTemplate(){
        
        // Today's Start (00:00:00)
        Date today = Date.today();
        String startToday = today.format(); // 'YYYY-MM-DD'

        // Today's End (23:59:59)
        String startTodayEnd = today.format(); // same date, API expects only date

        List<WhatsAppMetaTemplate__c> templateList = [
            SELECT Id, Id__c, Template_Name__c 
            FROM WhatsAppMetaTemplate__c 
            LIMIT 49999
        ];
        
        for (WhatsAppMetaTemplate__c temp : templateList) {
            TemplateInsightsController.getTemplateAnalytics(startToday, startTodayEnd, temp.Id__c);
        }
    }
}