force-app/main/default/objects/WhatsAppMetaTemplate__c/WhatsAppMetaTemplate__c.object-meta.xml
<CustomObject>
    <label>WhatsApp Meta Template</label>
    <nameField>
        <displayFormat>MT-{0000}</displayFormat>
        <label>Meta Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WhatsApp Meta Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/CorrectCategory__c.field-meta.xml
<CustomField>
    <fullName>CorrectCategory__c</fullName>
    <label>Correct Category</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <externalId>true</externalId>
    <label>Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/SubCategory__c.field-meta.xml
<CustomField>
    <fullName>SubCategory__c</fullName>
    <label>Sub Category</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/Template_Footer__c.field-meta.xml
<CustomField>
    <fullName>Template_Footer__c</fullName>
    <label>Template Footer</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/Template_Header__c.field-meta.xml
<CustomField>
    <fullName>Template_Header__c</fullName>
    <label>Template Header</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Template_Name__c</fullName>
    <label>Template Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateButtonOfferCode__c.field-meta.xml
<CustomField>
    <fullName>TemplateButtonOfferCode__c</fullName>
    <label>Template Button OfferCode</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateButtonPhone__c.field-meta.xml
<CustomField>
    <fullName>TemplateButtonPhone__c</fullName>
    <label>Template Button Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateButtonText__c.field-meta.xml
<CustomField>
    <fullName>TemplateButtonText__c</fullName>
    <label>Template Button Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateButtonType__c.field-meta.xml
<CustomField>
    <fullName>TemplateButtonType__c</fullName>
    <label>Template Button Type</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateButtonURL__c.field-meta.xml
<CustomField>
    <fullName>TemplateButtonURL__c</fullName>
    <label>Template Button URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateHeaderHandler__c.field-meta.xml
<CustomField>
    <fullName>TemplateHeaderHandler__c</fullName>
    <label>Template Header Handler</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WhatsAppMetaTemplate__c/fields/TemplateHeaderText__c.field-meta.xml
<CustomField>
    <fullName>TemplateHeaderText__c</fullName>
    <label>Template Header Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/TemplateBodyDmlQueueable.cls
public class TemplateBodyDmlQueueable implements Queueable {
    private List<WhatsAppMetaTemplate__c> messages;

    public TemplateBodyDmlQueueable(List<WhatsAppMetaTemplate__c> messages) {
        this.messages = messages;
    }

    public void execute(QueueableContext context) {
        for (WhatsAppMetaTemplate__c message : messages) {
            List<WhatsAppMetaTemplate__c> existingTemplates = [SELECT Id FROM WhatsAppMetaTemplate__c WHERE Id__c = :message.Id__c];

            if (!existingTemplates.isEmpty()) {
                WhatsAppMetaTemplate__c existingTemplate = existingTemplates[0];
                existingTemplate.Template_Name__c = message.Template_Name__c;
                existingTemplate.Template_Body__c = message.Template_Body__c;
                existingTemplate.Status__c = message.Status__c;
                existingTemplate.Template_Footer__c = message.Template_Footer__c;
                existingTemplate.Template_Header__c = message.Template_Header__c;
                existingTemplate.TemplateHeaderHandler__c = message.TemplateHeaderHandler__c;
                existingTemplate.TemplateHeaderText__c = message.TemplateHeaderText__c;
                //existingTemplate.SubCategory__c = message.SubCategory__c;
                existingTemplate.CorrectCategory__c = message.CorrectCategory__c;
                existingTemplate.TemplateButtonType__c = message.TemplateButtonType__c;
                existingTemplate.TemplateButtonText__c = message.TemplateButtonText__c;
                existingTemplate.TemplateButtonOfferCode__c = message.TemplateButtonOfferCode__c;
                existingTemplate.TemplateButtonPhone__c = message.TemplateButtonPhone__c;
                existingTemplate.TemplateButtonURL__c = message.TemplateButtonURL__c;
                update existingTemplate;
            } else {
                insert message;
            }
        }
    }
}